const chatTypes = {
  MESSAGE_SEND: "CHAT_MESSAGE_SEND",
  MESSAGE_SEND_SUCCESS: "CHAT_MESSAGE_SEND_SUCCESS",
  MESSAGE_SEND_ERROR: "CHAT_MESSAGE_SEND_FAILURE",
  MESSAGE_RECEIVE: "CHAT_MESSAGE_RECEIVE",
  MESSAGE_RECEIVE_SUCCESS: "CHAT_MESSAGE_RECEIVE_SUCCESS",
  MESSAGE_RECEIVE_ERROR: "CHAT_MESSAGE_RECEIVE_ERROR",
  // TODO - create more chat action types
};

export default chatTypes;
