const chatTypes = {
  MESSAGE_SEND: "CHAT_MESSAGE_SEND",
  MESSAGE_LOAD_GROUP_MESSAGES: "CHAT_MESSAGE_LOAD_GROUP_MESSAGES",
  GROUP_SET_ACTIVE: "CHAT_GROUP_SET_ACTIVE",
  MESSAGE_RECEIVE: "CHAT_MESSAGE_RECEIVE",
  // TODO - create more chat action types
};

export default chatTypes;
